SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
    FROM REST_INFO I
        , (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
                FROM REST_INFO
                GROUP BY FOOD_TYPE) T
    WHERE I.FAVORITES(+) = T.FAVORITES
        AND I.FOOD_TYPE IN (T.FOOD_TYPE)
    ORDER BY FOOD_TYPE DESC
;